apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: develop
servers: 1
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 8080:8080
    nodeFilters:
      - loadbalancer
registries:
  create:
    name: k3d-registry.127.0.0.1.nip.io
    host: 127.0.0.1 
    hostPort: "5000"
options:
  k3d:
    wait: true
    timeout: "60s"
