apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: develop
servers: 1
agents: 2
image: k8snutshell.azurecr.io/rancher/k3s:v1.24.4-k3s1
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 8080:8080
    nodeFilters:
      - loadbalancer
registries:
  create:
    image: k8snutshell.azurecr.io/registry:2
    name: k3d-registry.127.0.0.1.nip.io
    host: 127.0.0.1 
    hostPort: "5000"
  config: |
    mirrors:
      docker.io:
        endpoint:
          - https://k8snutshell.azurecr.io
options:
  k3d:
    wait: true
    timeout: "60s"
